export const toolNameMapping: Record<string, string> = {
    "open_web_browser": "Open Browser",
    "type_text_at": "Type Text",
    "click_at": "Click",
    "scroll_document": "Scroll",
    "scroll_at": "Scroll",
    "MESSAGE": "Message",
    "take_screenshot": "Screenshot",
    "close_browser": "Close Browser",
    "wait": "Wait",
    "extract_text": "Extract Text",
    "navigate": "Navigate",
    "wait_5_seconds": "Wait 5 Seconds",
    "go_back": "Go Back",
    "go_forward": "Go Forward",
    "search": "Search",
    "key_combination": "Key Combination",
    "hover_at": "Hover",
  };